project:
  type: website
  output-dir: docs

website:
  title: "Gabriele Midolo"
  navbar:
    left:
      - icon: house-door-fill
        href: index.qmd
        text: Home
      - icon: person-lines-fill
        href: cv.qmd
        text: CV
      - icon: file-bar-graph-fill
        href: projects.qmd
        text: Projects
      - icon: envelope-at-fill
        href: contact_me.qmd
        text: Contact me
    logo: imgs/butvec.logo.svg
    search: true
    right:
      - text: "{{< iconify fa6-brands linkedin >}}"
        href: "https://www.linkedin.com/in/gabriele-midolo-a49a99158"
      - text: "{{< iconify fa6-brands twitter >}}"
        href: "https://twitter.com/gabriele_midolo"
      - text: "{{< iconify academicons researchgate-square >}}"
        href: "https://www.researchgate.net/profile/Gabriele-Midolo"
      - text: "{{< iconify academicons google-scholar-square >}}"
        href: "https://scholar.google.com/citations?user=E8yonpAAAAAJ&hl"
      - text: "{{< iconify academicons orcid >}}"
        href: "https://orcid.org/0000-0003-1316-2546"


format:
  html:
    theme: flatly
    toc: true

editor: visual
